docs: add keyclock example
Hebilicious/authjs-nuxt pull request #49
Opened 2023-07-26 13:51 UTC by dissy123

### 🔗 Linked issue

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [X] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Changed appendHeader to setHeader to make it work got the following error with keycloak:

`
playground_keycloak:dev: [nuxt] [request error] [unhandled] [500] event.node.res.appendHeader is not a function
playground_keycloak:dev:   at respondWithResponse (./.nuxt/dev/index.mjs:851:22)  
playground_keycloak:dev:   at ./.nuxt/dev/index.mjs:890:12  
playground_keycloak:dev:   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
playground_keycloak:dev:   at async Object.handler (/Users/matthiasdollfuss/00_Dev/authjs-nuxt-new/node_modules/.pnpm/h3@1.7.1/node_modules/h3/dist/index.mjs:1284:19)  
playground_keycloak:dev:   at async Server.toNodeHandle (/Users/matthiasdollfuss/00_Dev/authjs-nuxt-new/node_modules/.pnpm/h3@1.7.1/node_modules/h3/dist/index.mjs:1359:7)
playground_keycloak:dev: [nuxt] [request error] [unhandled] [500] event.node.res.appendHeader is not a function
`

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2023-07-26 19:12 UTC, Hebilicious requested changes
Thanks for contributing a keycloak example, however this fix isn't right as it would break other things. 

Could you provide an issue with a reproduction of your error please ?

2023-07-27 06:05 UTC, dissy123 commented
Oh Sure, sorry!

https://github.com/Hebilicious/authjs-nuxt/issues/50

here is the reproduction! =)

2023-08-10 15:54 UTC, Hebilicious approved these changes

2023-08-10 15:56 UTC, merged

2023-08-10 15:56 UTC, Hebilicious commented
@dissy123 Thanks for the contribution 🤟🏽